// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pump2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gpu                  bool     `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Tf                   bool     `protobuf:"varint,3,opt,name=tf,proto3" json:"tf,omitempty"`
	Torch                bool     `protobuf:"varint,4,opt,name=torch,proto3" json:"torch,omitempty"`
	TfVersion            string   `protobuf:"bytes,5,opt,name=tfVersion,proto3" json:"tfVersion,omitempty"`
	TorchVersion         string   `protobuf:"bytes,6,opt,name=torchVersion,proto3" json:"torchVersion,omitempty"`
	Dependence           string   `protobuf:"bytes,7,opt,name=dependence,proto3" json:"dependence,omitempty"`
	UseToTest            bool     `protobuf:"varint,8,opt,name=useToTest,proto3" json:"useToTest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildInfo) Reset()         { *m = BuildInfo{} }
func (m *BuildInfo) String() string { return proto.CompactTextString(m) }
func (*BuildInfo) ProtoMessage()    {}
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *BuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildInfo.Unmarshal(m, b)
}
func (m *BuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildInfo.Marshal(b, m, deterministic)
}
func (m *BuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildInfo.Merge(m, src)
}
func (m *BuildInfo) XXX_Size() int {
	return xxx_messageInfo_BuildInfo.Size(m)
}
func (m *BuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuildInfo proto.InternalMessageInfo

func (m *BuildInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildInfo) GetGpu() bool {
	if m != nil {
		return m.Gpu
	}
	return false
}

func (m *BuildInfo) GetTf() bool {
	if m != nil {
		return m.Tf
	}
	return false
}

func (m *BuildInfo) GetTorch() bool {
	if m != nil {
		return m.Torch
	}
	return false
}

func (m *BuildInfo) GetTfVersion() string {
	if m != nil {
		return m.TfVersion
	}
	return ""
}

func (m *BuildInfo) GetTorchVersion() string {
	if m != nil {
		return m.TorchVersion
	}
	return ""
}

func (m *BuildInfo) GetDependence() string {
	if m != nil {
		return m.Dependence
	}
	return ""
}

func (m *BuildInfo) GetUseToTest() bool {
	if m != nil {
		return m.UseToTest
	}
	return false
}

type BuildResult struct {
	BuildStats           bool     `protobuf:"varint,1,opt,name=buildStats,proto3" json:"buildStats,omitempty"`
	ImageName            string   `protobuf:"bytes,2,opt,name=imageName,proto3" json:"imageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResult) Reset()         { *m = BuildResult{} }
func (m *BuildResult) String() string { return proto.CompactTextString(m) }
func (*BuildResult) ProtoMessage()    {}
func (*BuildResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *BuildResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResult.Unmarshal(m, b)
}
func (m *BuildResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResult.Marshal(b, m, deterministic)
}
func (m *BuildResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResult.Merge(m, src)
}
func (m *BuildResult) XXX_Size() int {
	return xxx_messageInfo_BuildResult.Size(m)
}
func (m *BuildResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResult.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResult proto.InternalMessageInfo

func (m *BuildResult) GetBuildStats() bool {
	if m != nil {
		return m.BuildStats
	}
	return false
}

func (m *BuildResult) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

type NodeInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

type NodeStat struct {
	NodeStats            bool     `protobuf:"varint,1,opt,name=nodeStats,proto3" json:"nodeStats,omitempty"`
	NodeHealth           string   `protobuf:"bytes,2,opt,name=nodeHealth,proto3" json:"nodeHealth,omitempty"`
	BuildNum             int32    `protobuf:"varint,3,opt,name=buildNum,proto3" json:"buildNum,omitempty"`
	Cpu                  int32    `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	LoadAvg              float32  `protobuf:"fixed32,5,opt,name=loadAvg,proto3" json:"loadAvg,omitempty"`
	CpuFreq              float32  `protobuf:"fixed32,6,opt,name=cpuFreq,proto3" json:"cpuFreq,omitempty"`
	Memory               int32    `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	MemoryFree           int32    `protobuf:"varint,8,opt,name=memoryFree,proto3" json:"memoryFree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStat) Reset()         { *m = NodeStat{} }
func (m *NodeStat) String() string { return proto.CompactTextString(m) }
func (*NodeStat) ProtoMessage()    {}
func (*NodeStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *NodeStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStat.Unmarshal(m, b)
}
func (m *NodeStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStat.Marshal(b, m, deterministic)
}
func (m *NodeStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStat.Merge(m, src)
}
func (m *NodeStat) XXX_Size() int {
	return xxx_messageInfo_NodeStat.Size(m)
}
func (m *NodeStat) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStat.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStat proto.InternalMessageInfo

func (m *NodeStat) GetNodeStats() bool {
	if m != nil {
		return m.NodeStats
	}
	return false
}

func (m *NodeStat) GetNodeHealth() string {
	if m != nil {
		return m.NodeHealth
	}
	return ""
}

func (m *NodeStat) GetBuildNum() int32 {
	if m != nil {
		return m.BuildNum
	}
	return 0
}

func (m *NodeStat) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *NodeStat) GetLoadAvg() float32 {
	if m != nil {
		return m.LoadAvg
	}
	return 0
}

func (m *NodeStat) GetCpuFreq() float32 {
	if m != nil {
		return m.CpuFreq
	}
	return 0
}

func (m *NodeStat) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *NodeStat) GetMemoryFree() int32 {
	if m != nil {
		return m.MemoryFree
	}
	return 0
}

func init() {
	proto.RegisterType((*BuildInfo)(nil), "pump2.BuildInfo")
	proto.RegisterType((*BuildResult)(nil), "pump2.BuildResult")
	proto.RegisterType((*NodeInfo)(nil), "pump2.NodeInfo")
	proto.RegisterType((*NodeStat)(nil), "pump2.NodeStat")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x2f, 0xb9, 0xdb, 0x5e, 0x32, 0x8a, 0x1e, 0x83, 0xc8, 0x52, 0x44, 0x8e, 0x3c, 0xdd,
	0x53, 0x91, 0x8a, 0x1f, 0x40, 0x1f, 0x8a, 0x45, 0x28, 0xb2, 0x16, 0xdf, 0xd3, 0x64, 0xd2, 0x16,
	0x92, 0xec, 0x9a, 0xec, 0x0a, 0x7e, 0x52, 0xdf, 0xfd, 0x24, 0x32, 0x93, 0xa4, 0xcd, 0xbd, 0xcd,
	0xff, 0x97, 0xc9, 0xec, 0xee, 0x8f, 0x81, 0xb4, 0x73, 0xc5, 0xca, 0x75, 0xd6, 0x5b, 0x54, 0x2e,
	0x34, 0x6e, 0x9d, 0xfd, 0x8d, 0x20, 0xfd, 0x12, 0xce, 0x75, 0xb9, 0x6d, 0x2b, 0x8b, 0x08, 0x77,
	0x6d, 0xde, 0x90, 0x8e, 0x1e, 0xa3, 0xa7, 0xd4, 0x48, 0x8d, 0x0f, 0x70, 0x7b, 0x74, 0x41, 0xc7,
	0x8f, 0xd1, 0x53, 0x62, 0xb8, 0xc4, 0x57, 0x10, 0xfb, 0x4a, 0xdf, 0x0a, 0x88, 0x7d, 0x85, 0x6f,
	0x40, 0x79, 0xdb, 0x15, 0x27, 0x7d, 0x27, 0x68, 0x08, 0xf8, 0x0e, 0x52, 0x5f, 0xfd, 0xa4, 0xae,
	0x3f, 0xdb, 0x56, 0x2b, 0x19, 0x78, 0x05, 0x98, 0xc1, 0x4b, 0x69, 0x9b, 0x1a, 0x16, 0xd2, 0xf0,
	0x8c, 0xe1, 0x7b, 0x80, 0x92, 0x1c, 0xb5, 0x25, 0xb5, 0x05, 0xe9, 0x7b, 0xe9, 0x98, 0x11, 0x3e,
	0x21, 0xf4, 0xb4, 0xb7, 0x7b, 0xea, 0xbd, 0x4e, 0xe4, 0xec, 0x2b, 0xc8, 0xbe, 0xc1, 0x0b, 0x79,
	0x98, 0xa1, 0x3e, 0xd4, 0x9e, 0x87, 0x1d, 0x38, 0xfe, 0xf0, 0xb9, 0xef, 0xe5, 0x81, 0x89, 0x99,
	0x11, 0x1e, 0x76, 0x6e, 0xf2, 0x23, 0xed, 0xf8, 0xfd, 0xf1, 0x70, 0xdd, 0x0b, 0xc8, 0x00, 0x92,
	0x9d, 0x2d, 0x89, 0x25, 0x65, 0xff, 0xa2, 0x21, 0xf0, 0x7f, 0xfc, 0x5b, 0x3b, 0xd6, 0xd3, 0xd4,
	0x2b, 0xe0, 0x43, 0x39, 0x7c, 0xa5, 0xbc, 0xf6, 0xa7, 0x71, 0xea, 0x8c, 0xe0, 0x12, 0x12, 0xb9,
	0xc2, 0x2e, 0x34, 0xe2, 0x53, 0x99, 0x4b, 0x66, 0xef, 0x85, 0x0b, 0xe2, 0x54, 0x19, 0x2e, 0x51,
	0xc3, 0x7d, 0x6d, 0xf3, 0xf2, 0xf3, 0xef, 0xa3, 0xf8, 0x8c, 0xcd, 0x14, 0xf9, 0x4b, 0xe1, 0xc2,
	0xa6, 0xa3, 0x5f, 0x22, 0x32, 0x36, 0x53, 0xc4, 0xb7, 0xb0, 0x68, 0xa8, 0xb1, 0xdd, 0x1f, 0xf1,
	0xa7, 0xcc, 0x98, 0xf8, 0x66, 0x43, 0xb5, 0xe9, 0x88, 0x44, 0x9e, 0x32, 0x33, 0xb2, 0x76, 0xa0,
	0xbe, 0xf3, 0x82, 0xe0, 0xa7, 0x51, 0xe3, 0x96, 0x5d, 0xf4, 0xf8, 0xb0, 0x92, 0xbd, 0x59, 0x5d,
	0x76, 0x66, 0x89, 0x73, 0x32, 0xc8, 0xce, 0x6e, 0xf0, 0x03, 0xc0, 0xe4, 0x28, 0xf4, 0xf8, 0x7a,
	0xec, 0x99, 0x1c, 0x2e, 0xe7, 0x80, 0x7b, 0xb2, 0x9b, 0xc3, 0x42, 0xf6, 0xf2, 0xe3, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0c, 0x31, 0x61, 0xd6, 0xa4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Pump2Client is the client API for Pump2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Pump2Client interface {
	BuildImages(ctx context.Context, in *BuildInfo, opts ...grpc.CallOption) (*BuildResult, error)
	NodeStatus(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*NodeStat, error)
}

type pump2Client struct {
	cc *grpc.ClientConn
}

func NewPump2Client(cc *grpc.ClientConn) Pump2Client {
	return &pump2Client{cc}
}

func (c *pump2Client) BuildImages(ctx context.Context, in *BuildInfo, opts ...grpc.CallOption) (*BuildResult, error) {
	out := new(BuildResult)
	err := c.cc.Invoke(ctx, "/pump2.Pump2/BuildImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pump2Client) NodeStatus(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*NodeStat, error) {
	out := new(NodeStat)
	err := c.cc.Invoke(ctx, "/pump2.Pump2/NodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Pump2Server is the builder API for Pump2 service.
type Pump2Server interface {
	BuildImages(context.Context, *BuildInfo) (*BuildResult, error)
	NodeStatus(context.Context, *NodeInfo) (*NodeStat, error)
}

// UnimplementedPump2Server can be embedded to have forward compatible implementations.
type UnimplementedPump2Server struct {
}

func (*UnimplementedPump2Server) BuildImages(ctx context.Context, req *BuildInfo) (*BuildResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildImages not implemented")
}
func (*UnimplementedPump2Server) NodeStatus(ctx context.Context, req *NodeInfo) (*NodeStat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeStatus not implemented")
}

func RegisterPump2Server(s *grpc.Server, srv Pump2Server) {
	s.RegisterService(&_Pump2_serviceDesc, srv)
}

func _Pump2_BuildImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pump2Server).BuildImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pump2.Pump2/BuildImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pump2Server).BuildImages(ctx, req.(*BuildInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pump2_NodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pump2Server).NodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pump2.Pump2/NodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pump2Server).NodeStatus(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pump2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pump2.Pump2",
	HandlerType: (*Pump2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildImages",
			Handler:    _Pump2_BuildImages_Handler,
		},
		{
			MethodName: "NodeStatus",
			Handler:    _Pump2_NodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
